.var SCREEN_MEM = $0400
.var CHR_IN = $ffe4
.var CHR_OUT = $ffd2
.var CLS = $e544

.var INTERRUPT_REG = $DC0D
.var RASTER_SPRITE_INT_REG = $D01A
.var RASTER_LINE_MSB = $D011
.var SCREEN_MULTICOLOUR = $D016
.var RASTER_LINE = $D012
.var INTERRUPT_EXECUTION_LOW = $0314
.var INTERRUPT_EXECUTION_HIGH = $0315
.var INTERRUPT_STATUS = $D019
.var SYS_IRQ_HANDLER = $EA31

.var JPORT2 = $DC00
